app/controllers/NewsController.php
<?php

namespace app\controllers;

use yii\easyii\models\Tag;
use yii\easyii\modules\article\api\Article;

class NewsController extends \yii\web\Controller
{
    /*public function actionIndex()
    {
        return $this->render('index');
    }*/

    /**
     * Список постов
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $news = Article::cat('news');
        if(!$news){
            throw new \yii\web\NotFoundHttpException('News category not found.');
        }
        //$tags = Tag::find()->orderBy('frequency DESC')->limit(10)->asArray()->all();

        return $this->render('index', [
            'news' => $news->getItems([
                'pagination' => ['pageSize' => 10],
            ]),
            'cat' => $news,
//            'tags'=>$tags,
        ]);
    }

    /**
     * Полный текст поста
     * @param string $slug
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionView($slug)
    {
        $cat = Article::cat('news');
        if(!$cat){
            throw new \yii\web\NotFoundHttpException('Article category not found.');
        }
        $article = Article::get($slug);
        if(!$article){
            throw new \yii\web\NotFoundHttpException('Article not found.');
        }

        return $this->render('view', [
            'article' => $article,
        ]);
    }

}

app/views/news/_index.php
<?php
/**
 * Created by PhpStorm.
 * User: b059a
 * Date: 11.12.2017
 * Time: 21:33
 */
/** @var $news \yii\easyii\modules\article\api\CategoryObject[] */
?>
<section class="latest-news pad-40">
    <div class="container modifications__container">
        <h1 class="modifications__title wow fadeInLeft">Новости</h1>
        <div class="news-posts-wrap flex">

            <?php foreach ($news as $item): ?>
                <div class="news-cards flex-col-4 wow fadeInUp">
                    <div class="news-cards-single flex advantages__container">
                        <div class="news-cards-image flex-col-12"
                             style="background-image: url('<?= $item->thumb(424, 200) ?>');">
                        </div>
                        <div class="news-cards-info flex-col-12">
                            <a href="<?= \yii\helpers\Url::to(['/news/view', 'slug' => $item->slug]) ?>">
                                <h3><?= $item->title ?></h3>
                                <p class="post-snippet"><?= $item->short ?></p>
                            </a>
                            <?php if (strlen($item->source) > 0): ?>
                                <p class="post-source">
                                    Источник: <?=
                                    \yii\helpers\Html::a(
                                        strlen($item->source) > 40
                                            ? $item->getSource(40) . '…'
                                            : $item->source,
                                        $item->source, [
                                        "rel" => "nofollow",
                                        "target" => "_blank",
                                    ])
                                    ?>
                                </p>
                            <?php endif; ?>
                            <p class="post-by"><?= $item->date ?></p>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

app/views/news/index.php
<?php
/**
 * User: Alexander Popov <b059ae@gmail.com>
 * Date: 20.07.2017
 * Time: 23:19
 */
/** @var $cat \yii\easyii\modules\article\api\CategoryObject */
/** @var $news \yii\easyii\modules\article\api\CategoryObject[] */
$this->registerMetaTag([
    'name' => 'description',
    'content' => $cat->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $cat->seo('keywords')
]);
$this->title = $cat->seo('title', $cat->title);
?>
<div class="pad-60">
    <?= $this->render('//news/_index', ['news' => $news]); ?>
</div>

app/views/news/view.php
<?php
/**
 * User: Alexander Popov <b059ae@gmail.com>
 * Date: 20.07.2017
 * Time: 23:19
 */
/** @var $article \yii\easyii\modules\article\api\ArticleObject */
$this->registerMetaTag([
    'name' => 'description',
    'content' => $article->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $article->seo('keywords')
]);
$this->title = $article->seo('title', $article->title);
?>
<section class="grey news-blog pad-100">
    <div class="container modifications__container">
        <h1 class="modifications__title"><?= $article->title ?></h1>
        <div class="wrap small-wrap flex flex-with-gutter">
            <div class="flex-col-12 right">
                <div class="addthis_inline_share_toolbox"></div>
            </div>
            <div class="flex-col-2">
                <p class="post-by"><?= $article->date ?></p>
            </div>

            <div class="flex-col-10">
                <?= $article->text ?>
                <?php if (strlen($article->source) > 0): ?>
                    <p>
                        Источник: <?=
                        \yii\helpers\Html::a(
                            strlen($article->source) > 80
                                ? $article->getSource(80) . '…'
                                : $article->source,
                            $article->source, [
                            "rel" => "nofollow",
                            "target" => "_blank",
                        ])
                        ?>
                    </p>
                <?php endif; ?>
                <div class="buttn-wrap">
                    <a href="<?= \yii\helpers\Url::to(['/news']) ?>" class="button-primary">Список новостей</a>
                </div>
            </div>
        </div>
    </div>

</section>